# Generated by Django 3.1.2 on 2021-11-25 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(regex='^[\\w.@+\\- ]+$')])),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('ip_address', models.TextField(default='')),
                ('country', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('image_upload', models.ImageField(upload_to='image')),
            ],
        ),
    ]
