# Generated by Django 3.1.2 on 2021-11-25 14:47

from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_auto_20211125_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='full_name',
            field=models.CharField(blank=True, max_length=17, verbose_name=re.compile('^(Mr\\.|Mrs\\.|Ms\\.) ([a-z]+)( [a-z]+)( [a-z]+)$', 2)),
        ),
    ]
